#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="$2";HOSTNAME=$(hostname -f);
[[ -f $DOKKU_ROOT/$APP/ENV ]] && source $DOKKU_ROOT/$APP/ENV
echo "-----> Notifying Hipchat of Release ..."
echo "Build Complete for $APP on $HOSTNAME" | HIPCHAT_COLOR=green $PLUGIN_PATH/hipchat/hipchat >/dev/null
